### ISSUE TITLE
The deploy works, but the website doesn't.

### ISSUE THREAD

**Issue by victorperez2911** [yzwijsen/deploy-uptime-kuma-azure#1]
Hello @yzwijsen 

By default, uptime kuma listens to port 3001, but azure web app only listens and forwards ports 80 and 443.

I don't see any reference to http ports in the bicep file

I miss something ?

Right after deploying the bicep file, the url of the azure website does not work.

**Comment by nreddipalle** [comment]
@victorperez2911 are you able to figure out this problem? I am facing same error.. deployed fine but could not access it.

**Comment by victorperez2911** [comment]
> @victorperez2911 are you able to figure out this problem? I am facing same error.. deployed fine but could not access it.

Nope

**Comment by nreddipalle** [comment]
I made it work when I enabled web sockets to true and Always ON to true at app service configuration settings.

**Comment by victorperez2911** [comment]
> I made it work when I enabled web sockets to true and Always ON to true at app service configuration settings.

Bicep file create a "linux based" Web App, and this doesn't have the "Web Socket" option.
Researching, I discovered that Web Socket is active by default in Linux-based Web Apps.

However, it worked when activating "Always On".
